inherits = "base16_default"
"ui.cursor" = { fg = "white", bg = "gray" }
"ui.cursor.primary" = { fg = "black", bg = "white" }
"ui.selection" = { fg = "black", bg = "gray" }
"ui.selection.primary" = { fg = "white", bg = "gray" }
"ui.menu" = "white"
"ui.popup" = "gray"
"ui.statusline" = "white"
"ui.statusline.active" = "white"
"ui.statusline.inactive" = "gray"
"operator" = "red"
"variable" = "white"
"variable.other.member" = "gray"

# inherits = "onedark"
# "ui.cursor" = { fg = "black", bg = "light-gray" }
# "ui.cursor.primary" = { fg = "black", bg = "white" }

# "ui.selection" = { modifiers = ["reversed"] }
