theme = "yesmydark"
[keys.normal]
C-c = ":q"
C-s = ":w"
C-y = "save_selection"
'#' = "toggle_comments"
'{' = "goto_prev_paragraph"
'}' = "goto_next_paragraph"
'A-x' = "extend_line_above"
'A-*' = "make_search_word_bounded"
[keys.select]
C-c = ":q"
C-s = ":w"
C-y = "save_selection"
'#' = "toggle_comments"
'{' = "goto_prev_paragraph"
'}' = "goto_next_paragraph"
'A-x' = "extend_line_above"
'A-*' = "make_search_word_bounded"
[editor]
auto-info = false
auto-pairs = false
auto-format = false
line-number = "relative"
bufferline = "multiple"
scrolloff = 1
[editor.statusline]
center = ["total-line-numbers", "primary-selection-length"]
[editor.lsp]
auto-signature-help = false
[editor.cursor-shape]
insert = "bar"
select = "underline"
[editor.file-picker]
max-depth = 4
hidden = false
