[[language]]
name = "markdown"
file-types = ["md", "markdown", "EDIT_DESCRIPTION"]
comment-token = "<!--"

[[language]]
name = "sel"
scope = "source.sel"
file-types = [{ suffix = ".sel" }]
roots = []
comment-token = "#"
indent = { tab-width = 2, unit = "  " }
[[grammar]]
name = "sel"
source = { git = "https://github.com/naclsn/sel.git", rev = "075f72d6cdc84af8014b84c95f8f8c772109fb6a" }
